# load the dataset
import pandas as pd

Cleaned_data=pd.read_excel("D:\SCHOOL PROJECTS\Internship projects\Cleaned_Dataset.xlsx")

# Exploratory Data Analysis (EDA)
#===calculate basic statistics
basic_stats = Cleaned_data.describe()
print(basic_stats)

 # checking for outliers in numeric columns using boxplot
import matplotlib.pyplot as plt
numeric_columns = ['Quantity', 'UnitPrice', 'ItemsInCart', 'TotalPrice']
for col in numeric_columns:
    plt.figure(figsize=(10, 6))
    plt.boxplot(Cleaned_data[col])
    plt.title(f'Boxplot of {col}')
    plt.ylabel(col)
    plt.savefig(f'boxplot_{col}.png')  # Save the boxplot as a PNG file
    plt.show()


# Total items sold by each product category
total_items_sold = Cleaned_data.groupby('Product')['Quantity'].sum()
print(total_items_sold)

# Total revenue generated by each product category
total_revenue = Cleaned_data.groupby('Product')['TotalPrice'].sum()
print(total_revenue)

# total number of each coupon
total_coupons = Cleaned_data['CouponCode'].value_counts()
print(total_coupons)

#total coupon used by each product category
total_coupon_used = Cleaned_data.groupby('Product')['CouponCode'].count()
print(total_coupon_used)

# total revenue generated by each coupon code
total_revenue_by_coupon = Cleaned_data.groupby('CouponCode')['TotalPrice'].sum()
print(total_revenue_by_coupon)

# count each order status
total_order_status = Cleaned_data['OrderStatus'].value_counts()
print(total_order_status)

#order status by coupon code
order_status_by_coupon = Cleaned_data.groupby('CouponCode')['OrderStatus'].value_counts()
print(order_status_by_coupon)

# checking for cancellation and return rate of each product category
cancellation_return_rate = Cleaned_data.groupby('Product')['OrderStatus'].value_counts(normalize="index")*100
print(cancellation_return_rate)

# does unit price affect cancellation?
unit_price_by_cancellation = Cleaned_data.groupby('OrderStatus')['UnitPrice'].mean()
print(unit_price_by_cancellation)

# check if shipping address affects cancellation(address with the highest cancellation rate)
shipping_address_cancellation = Cleaned_data.groupby('ShippingAddress')['OrderStatus'].value_counts(normalize="index")*100
print(shipping_address_cancellation)

#  products with the highest number of cancellation
highest_cancellation_return = Cleaned_data[Cleaned_data['OrderStatus'].isin(['Cancelled'])].groupby('Product')['OrderStatus'].count().sort_values(ascending=False)
print(highest_cancellation_return)

# products with the highest number of returns
highest_return = Cleaned_data[Cleaned_data['OrderStatus'].isin(['Returned'])].groupby('Product')['OrderStatus'].count().sort_values(ascending=False)
print(highest_return)

# products by order date
products_by_date = Cleaned_data.groupby('Date')['Product'].count()
print(products_by_date)

# month with the highest revenue
Cleaned_data['Date'] = pd.to_datetime(Cleaned_data['Date'])
monthly_revenue = Cleaned_data.groupby(Cleaned_data['Date'].dt.month)['TotalPrice'].sum()
print(monthly_revenue)

# what is mostly sold in each month
most_sold_by_month = Cleaned_data.groupby(Cleaned_data['Date'].dt.month)['Product'].agg(lambda x: x.value_counts().index[0])
print(most_sold_by_month)

# visualize the monthly revenue of each product category
import seaborn as sns
# Create a 'Year-Month' column for accurate time-series plotting
Cleaned_data['YearMonth'] = Cleaned_data['Date'].dt.to_period('M')

plt.figure(figsize=(10, 5))
for product in Cleaned_data['Product'].unique():
    # Filter data for current product and group by YearMonth
    product_data = Cleaned_data[Cleaned_data['Product'] == product]
    monthly_rev = product_data.groupby('YearMonth')['TotalPrice'].sum()
    
    # Plot using the period index (preserves chronological order)
    sns.lineplot(x=monthly_rev.index.astype(str), y=monthly_rev.values, label=product, marker='o')

plt.xlabel('Year-Month')
plt.ylabel('Revenue ($)')
plt.title('Monthly Revenue Trend by Product (2023-2025)')
plt.xticks(rotation=45)
plt.legend(title='Product')
plt.tight_layout()
plt.savefig('monthly_revenue_trend_fixed.png', dpi=300)
plt.show()


